data:
  raw_data_path: "data/raw/en.openfoodfacts.org.products.csv.gz"
  processed_data_path: "data/processed/processed_dataset.csv"
  clean_data_path: "data/processed/clean_dataset.csv"
  clean_data_with_embed: "data/clean_dataset_with_embeddings.csv"
  data_with_clusters: "data/clean_dataset_clusters.csv"
  production_data_path: "data/production/database.csv"
  production_categorical_features_data_path: "data/production/categorical_features.csv"
  production_encoded_features_path: "data/production/production_encoded_features.csv"
  save_production_image_path: "data/production/database_image_api.csv"
  production_text_data_api_path: "data/production/database_text_api.csv"
  images_path: "data/product_images"
  image_url_column: "image_url"
  code_column: "code"
  embedding_prefix: "embedding"

training:
  mlflow_experiment_name: "foodstuffs-recommendation"
  mlflow_tracking_uri: "https://mlflow.luciole.dev"
  mlflow_model_name: "kmeans"
  encoding_method_name: "svd" # [svd, pca]
  n_clusters: 525

image_training:
  n_clusters: 300

recommandatons:
  top_n: 10
